
language: node_js

node_js:
  - '6'

install:
  - npm install --global package-alt-yaml
  - ynpm install

before_script:
  - chmod -R +x sh

before_deploy:
  - source ./sh/deploy/before.sh

after_deploy:
  - source ./sh/deploy/after.sh
