name: package-alt-yaml
description: Use package.yaml instead of package.json
version: 0.0.2
main: help.js
bin:
  package-alt-yaml: help.js
  npm-yaml: update.js
  ynpm: update.js
  npm-yaml-update: update.js
  ynpm-update: update.js
  npm-yaml-preserve: preserve.js
  ynpm-preserve: preserve.js
preferGlobal: true
author: Hoàng Văn Khải <hvksmr1996@gmail.com>
contributors:
  - Hoàng Văn Khải <hvksmr1996@gmail.com>
license: MIT
repository:
  type: git
  url: 'https://github.com/ksxnodeapps/package-alt-yaml.git'
dependencies:
  package-alt: ^0.0.5
  js-yaml: ^3.8.3
devDependencies:
  standard: ^10.0.1
scripts:
  remake-package-json: node sh/remake-package-json
  clean: bash 'sh/clean.sh'
  fix: bash 'sh/fix.sh'
  test: bash 'sh/test.sh'
keywords:
  - package.yaml
  - alternate
  - npm
  - npm-yaml
  - ynpm
bugs:
  url: 'https://github.com/ksxnodeapps/package-alt-yaml/issues'
homepage: 'https://github.com/ksxnodeapps/package-alt-yaml#readme'
